### ISSUE TITLE
Create elementary 6 AppCenter manifest

### ISSUE THREAD

**Issue by hanaral** [cassidyjames/ephemeral#283]
I've been trying to create one myself but cannot for the life of me figure out what's causing it to crash silently:
```
han@elementary-os-desktop-a67bc731:~/Documents/ephemeral-main$ flatpak run com.github.cassidyjames.ephemeral --g-fatal-warnings
Gtk-Message: 17:48:38.939: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:48:38.940: Failed to load module "canberra-gtk-module"
```
And here is the manifest I used to build:
```
app-id: com.github.cassidyjames.ephemeral
runtime: io.elementary.Platform
runtime-version: 'daily'
sdk: io.elementary.Sdk
command: com.github.cassidyjames.ephemeral
finish-args:
  - '--share=network'

  - '--share=ipc'
  - '--socket=fallback-x11'
  - '--socket=wayland'

  - '--talk-name=org.gtk.vfs.*'
  - '--talk-name=org.gnome.SettingsDaemon'
  - '--talk-name=org.elementary.Contractor'

  # - '--metadata=X-DConf=migrate-path=/com/github/cassidyjames/'
modules:
  # - name: handy
  #   buildsystem: meson
  #   sources:
  #     - type: git
  #       url: https://gitlab.gnome.org/GNOME/libhandy.git
  #       tag: '1.0.0'

  - name: libdazzle
    buildsystem: meson
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/libdazzle.git
        tag: '3.40.0'

  - name: ephemeral
    buildsystem: meson
    sources:
      - type: dir
        path: .
```
@cassidyjames would you be able to check what might be up if you have the time?
